"use strict";
// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=ts"
// @generated from file goods_dispatches.proto (package Genesis, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", ***REMOVED*** value: true ***REMOVED***);
exports.GoodsDispatchesService = void 0;
const goods_dispatches_pb_js_1 = require("./goods_dispatches_pb.js");
const base_pb_js_1 = require("./base_pb.js");
const protobuf_1 = require("@bufbuild/protobuf");
const families_pb_js_1 = require("./families_pb.js");
/**
 *
 * Describes the common methods applicable on each goods dispatch
 *
 * @generated from service Genesis.GoodsDispatchesService
 */
exports.GoodsDispatchesService = ***REMOVED***
    typeName: "Genesis.GoodsDispatchesService",
    methods: ***REMOVED***
        /**
         * Create and send for verification
         *
         * @generated from rpc Genesis.GoodsDispatchesService.Create
         */
        create: ***REMOVED***
            name: "Create",
            I: goods_dispatches_pb_js_1.GoodsDispatchesServiceCreateRequest,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * Create and save as draft
         *
         * @generated from rpc Genesis.GoodsDispatchesService.Draft
         */
        draft: ***REMOVED***
            name: "Draft",
            I: goods_dispatches_pb_js_1.GoodsDispatchesServiceCreateRequest,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * Update draft
         *
         * @generated from rpc Genesis.GoodsDispatchesService.DraftUpdate
         */
        draftUpdate: ***REMOVED***
            name: "DraftUpdate",
            I: goods_dispatches_pb_js_1.GoodsDispatchesServiceUpdateRequest,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * Send for verification
         *
         * @generated from rpc Genesis.GoodsDispatchesService.SendForVerification
         */
        sendForVerification: ***REMOVED***
            name: "SendForVerification",
            I: base_pb_js_1.IdentifierWithUserComment,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * Verify
         *
         * @generated from rpc Genesis.GoodsDispatchesService.Verify
         */
        verify: ***REMOVED***
            name: "Verify",
            I: base_pb_js_1.IdentifierWithUserComment,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * Approve
         *
         * @generated from rpc Genesis.GoodsDispatchesService.Approve
         */
        approve: ***REMOVED***
            name: "Approve",
            I: base_pb_js_1.IdentifierWithUserComment,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * Send For Revision
         *
         * @generated from rpc Genesis.GoodsDispatchesService.SendForRevision
         */
        sendForRevision: ***REMOVED***
            name: "SendForRevision",
            I: base_pb_js_1.IdentifierWithUserComment,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * Update revision
         *
         * @generated from rpc Genesis.GoodsDispatchesService.RevisionUpdate
         */
        revisionUpdate: ***REMOVED***
            name: "RevisionUpdate",
            I: goods_dispatches_pb_js_1.GoodsDispatchesServiceUpdateRequest,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * Halt
         *
         * @generated from rpc Genesis.GoodsDispatchesService.Halt
         */
        halt: ***REMOVED***
            name: "Halt",
            I: base_pb_js_1.IdentifierWithUserComment,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * Discard
         *
         * @generated from rpc Genesis.GoodsDispatchesService.Discard
         */
        discard: ***REMOVED***
            name: "Discard",
            I: base_pb_js_1.IdentifierWithUserComment,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * Restore
         *
         * @generated from rpc Genesis.GoodsDispatchesService.Restore
         */
        restore: ***REMOVED***
            name: "Restore",
            I: base_pb_js_1.IdentifierWithUserComment,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * Complete
         *
         * @generated from rpc Genesis.GoodsDispatchesService.Complete
         */
        complete: ***REMOVED***
            name: "Complete",
            I: base_pb_js_1.IdentifierWithUserComment,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * Repeat
         *
         * @generated from rpc Genesis.GoodsDispatchesService.Repeat
         */
        repeat: ***REMOVED***
            name: "Repeat",
            I: base_pb_js_1.IdentifierWithUserComment,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * Reopen
         *
         * @generated from rpc Genesis.GoodsDispatchesService.Reopen
         */
        reopen: ***REMOVED***
            name: "Reopen",
            I: base_pb_js_1.IdentifierWithUserComment,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * Add comment
         *
         * @generated from rpc Genesis.GoodsDispatchesService.CommentAdd
         */
        commentAdd: ***REMOVED***
            name: "CommentAdd",
            I: base_pb_js_1.IdentifierWithUserComment,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * Send Email
         *
         * @generated from rpc Genesis.GoodsDispatchesService.SendEmail
         */
        sendEmail: ***REMOVED***
            name: "SendEmail",
            I: base_pb_js_1.IdentifierWithEmailAttributes,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * Autofill the goods dispatch
         *
         * @generated from rpc Genesis.GoodsDispatchesService.Autofill
         */
        autofill: ***REMOVED***
            name: "Autofill",
            I: goods_dispatches_pb_js_1.GoodsDispatchesServiceAutofillRequest,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * Checks if the Goods Dispatch can be marked as completed
         *
         * @generated from rpc Genesis.GoodsDispatchesService.IsCompletable
         */
        isCompletable: ***REMOVED***
            name: "IsCompletable",
            I: base_pb_js_1.Identifier,
            O: base_pb_js_1.BooleanResponse,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * Add an item to a goods dispatch
         *
         * @generated from rpc Genesis.GoodsDispatchesService.AddGoodsDispatchItem
         */
        addGoodsDispatchItem: ***REMOVED***
            name: "AddGoodsDispatchItem",
            I: goods_dispatches_pb_js_1.GoodsDispatchesServiceItemCreateRequest,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * Modify an item in a goods dispatch
         *
         * @generated from rpc Genesis.GoodsDispatchesService.ModifyGoodsDispatchItem
         */
        modifyGoodsDispatchItem: ***REMOVED***
            name: "ModifyGoodsDispatchItem",
            I: goods_dispatches_pb_js_1.GoodsDispatchesServiceItemUpdateRequest,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * Approve an item in a goods dispatch
         *
         * @generated from rpc Genesis.GoodsDispatchesService.ApproveGoodsDispatchItem
         */
        approveGoodsDispatchItem: ***REMOVED***
            name: "ApproveGoodsDispatchItem",
            I: base_pb_js_1.IdentifierWithUserComment,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * Delete an item in a goods dispatch
         *
         * @generated from rpc Genesis.GoodsDispatchesService.DeleteGoodsDispatchItem
         */
        deleteGoodsDispatchItem: ***REMOVED***
            name: "DeleteGoodsDispatchItem",
            I: base_pb_js_1.IdentifierWithUserComment,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * Reorder items in a goods dispatch
         *
         * @generated from rpc Genesis.GoodsDispatchesService.ReorderGoodsDispatchItems
         */
        reorderGoodsDispatchItems: ***REMOVED***
            name: "ReorderGoodsDispatchItems",
            I: base_pb_js_1.ReorderItemsRequest,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * View Goods Dispatch Item by ID
         *
         * @generated from rpc Genesis.GoodsDispatchesService.ViewGoodsDispatchItemByID
         */
        viewGoodsDispatchItemByID: ***REMOVED***
            name: "ViewGoodsDispatchItemByID",
            I: base_pb_js_1.Identifier,
            O: goods_dispatches_pb_js_1.GoodsDispatchItem,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * View Goods Dispatch Item by Inventory Hash
         *
         * @generated from rpc Genesis.GoodsDispatchesService.ViewGoodsDispatchItemByInventoryHash
         */
        viewGoodsDispatchItemByInventoryHash: ***REMOVED***
            name: "ViewGoodsDispatchItemByInventoryHash",
            I: base_pb_js_1.SimpleSearchReq,
            O: goods_dispatches_pb_js_1.GoodsDispatchItem,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * View approved goods dispatch items for given goods dispatch ID
         *
         * @generated from rpc Genesis.GoodsDispatchesService.ViewApprovedGoodsDispatchItems
         */
        viewApprovedGoodsDispatchItems: ***REMOVED***
            name: "ViewApprovedGoodsDispatchItems",
            I: base_pb_js_1.IdentifierWithSearchKey,
            O: goods_dispatches_pb_js_1.GoodsDispatchesItemsList,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * View unapproved goods dispatch items for given goods dispatch ID
         *
         * @generated from rpc Genesis.GoodsDispatchesService.ViewUnapprovedGoodsDispatchItems
         */
        viewUnapprovedGoodsDispatchItems: ***REMOVED***
            name: "ViewUnapprovedGoodsDispatchItems",
            I: base_pb_js_1.IdentifierWithSearchKey,
            O: goods_dispatches_pb_js_1.GoodsDispatchesItemsList,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * View the history of the goods dispatch item
         *
         * @generated from rpc Genesis.GoodsDispatchesService.ViewGoodsDispatchItemHistory
         */
        viewGoodsDispatchItemHistory: ***REMOVED***
            name: "ViewGoodsDispatchItemHistory",
            I: goods_dispatches_pb_js_1.GoodsDispatchItemHistoryRequest,
            O: goods_dispatches_pb_js_1.GoodsDispatchesItemsList,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * View by ID
         *
         * @generated from rpc Genesis.GoodsDispatchesService.ViewByID
         */
        viewByID: ***REMOVED***
            name: "ViewByID",
            I: base_pb_js_1.Identifier,
            O: goods_dispatches_pb_js_1.GoodsDispatch,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * View all
         *
         * @generated from rpc Genesis.GoodsDispatchesService.ViewAll
         */
        viewAll: ***REMOVED***
            name: "ViewAll",
            I: base_pb_js_1.ActiveStatus,
            O: goods_dispatches_pb_js_1.GoodsDispatchesList,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * View all with the given entity UUID
         *
         * @generated from rpc Genesis.GoodsDispatchesService.ViewAllForEntityUUID
         */
        viewAllForEntityUUID: ***REMOVED***
            name: "ViewAllForEntityUUID",
            I: base_pb_js_1.IdentifierUUID,
            O: goods_dispatches_pb_js_1.GoodsDispatchesList,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * View with pagination
         *
         * @generated from rpc Genesis.GoodsDispatchesService.ViewWithPagination
         */
        viewWithPagination: ***REMOVED***
            name: "ViewWithPagination",
            I: goods_dispatches_pb_js_1.GoodsDispatchesServicePaginationReq,
            O: goods_dispatches_pb_js_1.GoodsDispatchesServicePaginationResponse,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * View with pagination with the given entity UUID
         *
         * @generated from rpc Genesis.GoodsDispatchesService.ViewWithPaginationForEntityUUID
         */
        viewWithPaginationForEntityUUID: ***REMOVED***
            name: "ViewWithPaginationForEntityUUID",
            I: goods_dispatches_pb_js_1.GoodsDispatchesServiceEntityPaginationReq,
            O: goods_dispatches_pb_js_1.GoodsDispatchesServicePaginationResponse,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * View prospective families for the given goods dispatch
         *
         * @generated from rpc Genesis.GoodsDispatchesService.ViewProspectiveFamilies
         */
        viewProspectiveFamilies: ***REMOVED***
            name: "ViewProspectiveFamilies",
            I: base_pb_js_1.IdentifierWithSearchKey,
            O: families_pb_js_1.FamiliesList,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * View prospective goods dispatch item info for the given family ID and goods dispatch ID
         *
         * @generated from rpc Genesis.GoodsDispatchesService.ViewProspectiveGoodsDispatchItem
         */
        viewProspectiveGoodsDispatchItem: ***REMOVED***
            name: "ViewProspectiveGoodsDispatchItem",
            I: goods_dispatches_pb_js_1.GoodsDispatchItemProspectiveInfoRequest,
            O: goods_dispatches_pb_js_1.GoodsDispatchesServiceItemCreateRequest,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * View the associated sales invoice ID that is denoted by the identifier in the response for the goods dispatch that is denoted by the identifier in the request
         *
         * @generated from rpc Genesis.GoodsDispatchesService.ViewAssociatedSalesInvoiceID
         */
        viewAssociatedSalesInvoiceID: ***REMOVED***
            name: "ViewAssociatedSalesInvoiceID",
            I: base_pb_js_1.Identifier,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * Checks if the Goods Dispatch has been billed
         *
         * @generated from rpc Genesis.GoodsDispatchesService.IsBilled
         */
        isBilled: ***REMOVED***
            name: "IsBilled",
            I: base_pb_js_1.Identifier,
            O: base_pb_js_1.BooleanResponse,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * View already added quantities
         *
         * @generated from rpc Genesis.GoodsDispatchesService.ViewAddedFamilyQuantityForSource
         */
        viewAddedFamilyQuantityForSource: ***REMOVED***
            name: "ViewAddedFamilyQuantityForSource",
            I: goods_dispatches_pb_js_1.GoodsDispatchesServiceAlreadyAddedQuantityForSourceRequest,
            O: base_pb_js_1.DualQuantitiesResponse,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * View all that match the given search key
         *
         * @generated from rpc Genesis.GoodsDispatchesService.SearchAll
         */
        searchAll: ***REMOVED***
            name: "SearchAll",
            I: goods_dispatches_pb_js_1.GoodsDispatchesServiceSearchAllReq,
            O: goods_dispatches_pb_js_1.GoodsDispatchesList,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * View all that match the given filter criteria
         *
         * @generated from rpc Genesis.GoodsDispatchesService.Filter
         */
        filter: ***REMOVED***
            name: "Filter",
            I: goods_dispatches_pb_js_1.GoodsDispatchesServiceFilterReq,
            O: goods_dispatches_pb_js_1.GoodsDispatchesList,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * Count in status
         *
         * @generated from rpc Genesis.GoodsDispatchesService.CountInStatus
         */
        countInStatus: ***REMOVED***
            name: "CountInStatus",
            I: base_pb_js_1.CountInSLCStatusRequest,
            O: base_pb_js_1.CountResponse,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
***REMOVED***
***REMOVED***;
