"use strict";
// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=ts"
// @generated from file leaves_requests.proto (package Genesis, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.LeavesRequestsService = void 0;
const leaves_requests_pb_js_1 = require("./leaves_requests_pb.js");
const base_pb_js_1 = require("./base_pb.js");
const protobuf_1 = require("@bufbuild/protobuf");
/**
 *
 * Describes the common methods applicable on each leave request
 *
 * @generated from service Genesis.LeavesRequestsService
 */
exports.LeavesRequestsService = {
    typeName: "Genesis.LeavesRequestsService",
    methods: {
        /**
         * Create and send for verification
         *
         * @generated from rpc Genesis.LeavesRequestsService.Create
         */
        create: {
            name: "Create",
            I: leaves_requests_pb_js_1.LeavesRequestsServiceCreateRequest,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * Create and save as draft
         *
         * @generated from rpc Genesis.LeavesRequestsService.Draft
         */
        draft: {
            name: "Draft",
            I: leaves_requests_pb_js_1.LeavesRequestsServiceCreateRequest,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * Update draft
         *
         * @generated from rpc Genesis.LeavesRequestsService.DraftUpdate
         */
        draftUpdate: {
            name: "DraftUpdate",
            I: leaves_requests_pb_js_1.LeavesRequestsServiceUpdateRequest,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * Send for verification
         *
         * @generated from rpc Genesis.LeavesRequestsService.SendForVerification
         */
        sendForVerification: {
            name: "SendForVerification",
            I: base_pb_js_1.IdentifierWithUserComment,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * Verify
         *
         * @generated from rpc Genesis.LeavesRequestsService.Verify
         */
        verify: {
            name: "Verify",
            I: base_pb_js_1.IdentifierWithUserComment,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * Approve
         *
         * @generated from rpc Genesis.LeavesRequestsService.Approve
         */
        approve: {
            name: "Approve",
            I: base_pb_js_1.IdentifierWithUserComment,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * Send For Revision
         *
         * @generated from rpc Genesis.LeavesRequestsService.SendForRevision
         */
        sendForRevision: {
            name: "SendForRevision",
            I: base_pb_js_1.IdentifierWithUserComment,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * Update revision
         *
         * @generated from rpc Genesis.LeavesRequestsService.RevisionUpdate
         */
        revisionUpdate: {
            name: "RevisionUpdate",
            I: leaves_requests_pb_js_1.LeavesRequestsServiceUpdateRequest,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * Halt
         *
         * @generated from rpc Genesis.LeavesRequestsService.Halt
         */
        halt: {
            name: "Halt",
            I: base_pb_js_1.IdentifierWithUserComment,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * Discard
         *
         * @generated from rpc Genesis.LeavesRequestsService.Discard
         */
        discard: {
            name: "Discard",
            I: base_pb_js_1.IdentifierWithUserComment,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * Restore
         *
         * @generated from rpc Genesis.LeavesRequestsService.Restore
         */
        restore: {
            name: "Restore",
            I: base_pb_js_1.IdentifierWithUserComment,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * Complete
         *
         * @generated from rpc Genesis.LeavesRequestsService.Complete
         */
        complete: {
            name: "Complete",
            I: base_pb_js_1.IdentifierWithUserComment,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * Repeat
         *
         * @generated from rpc Genesis.LeavesRequestsService.Repeat
         */
        repeat: {
            name: "Repeat",
            I: base_pb_js_1.IdentifierWithUserComment,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * Add comment
         *
         * Send Email
         * rpc SendEmail (Identifier) returns (Identifier);
         *
         * @generated from rpc Genesis.LeavesRequestsService.CommentAdd
         */
        commentAdd: {
            name: "CommentAdd",
            I: base_pb_js_1.IdentifierWithUserComment,
            O: base_pb_js_1.Identifier,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * View by ID
         *
         * @generated from rpc Genesis.LeavesRequestsService.ViewByID
         */
        viewByID: {
            name: "ViewByID",
            I: base_pb_js_1.Identifier,
            O: leaves_requests_pb_js_1.LeaveRequest,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * View all
         *
         * @generated from rpc Genesis.LeavesRequestsService.ViewAll
         */
        viewAll: {
            name: "ViewAll",
            I: base_pb_js_1.ActiveStatus,
            O: leaves_requests_pb_js_1.LeavesRequestsList,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * View all with the given entity UUID
         *
         * @generated from rpc Genesis.LeavesRequestsService.ViewAllForEntityUUID
         */
        viewAllForEntityUUID: {
            name: "ViewAllForEntityUUID",
            I: base_pb_js_1.IdentifierUUID,
            O: leaves_requests_pb_js_1.LeavesRequestsList,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * View with pagination
         *
         * @generated from rpc Genesis.LeavesRequestsService.ViewWithPagination
         */
        viewWithPagination: {
            name: "ViewWithPagination",
            I: leaves_requests_pb_js_1.LeavesRequestsServicePaginationReq,
            O: leaves_requests_pb_js_1.LeavesRequestsServicePaginationResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * View with pagination with the given entity UUID
         *
         * @generated from rpc Genesis.LeavesRequestsService.ViewWithPaginationForEntityUUID
         */
        viewWithPaginationForEntityUUID: {
            name: "ViewWithPaginationForEntityUUID",
            I: leaves_requests_pb_js_1.LeavesRequestsServiceEntityPaginationReq,
            O: leaves_requests_pb_js_1.LeavesRequestsServicePaginationResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * View all that match the given search key
         *
         * @generated from rpc Genesis.LeavesRequestsService.SearchAll
         */
        searchAll: {
            name: "SearchAll",
            I: leaves_requests_pb_js_1.LeavesRequestsServiceSearchAllReq,
            O: leaves_requests_pb_js_1.LeavesRequestsList,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * View all that match the given filter criteria
         *
         * @generated from rpc Genesis.LeavesRequestsService.Filter
         */
        filter: {
            name: "Filter",
            I: leaves_requests_pb_js_1.LeavesRequestsServiceFilterReq,
            O: leaves_requests_pb_js_1.LeavesRequestsList,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * Count in status
         *
         * @generated from rpc Genesis.LeavesRequestsService.CountInStatus
         */
        countInStatus: {
            name: "CountInStatus",
            I: base_pb_js_1.CountInSLCStatusRequest,
            O: base_pb_js_1.CountResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
    }
};
