"use strict";
// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=ts"
// @generated from file logins.proto (package Genesis, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", ***REMOVED*** value: true ***REMOVED***);
exports.LoginService = void 0;
const logins_pb_js_1 = require("./logins_pb.js");
const protobuf_1 = require("@bufbuild/protobuf");
const base_pb_js_1 = require("./base_pb.js");
/**
 *
 * Describes the methods applicable on the login service
 *
 * @generated from service Genesis.LoginService
 */
exports.LoginService = ***REMOVED***
    typeName: "Genesis.LoginService",
    methods: ***REMOVED***
        /**
         * Login using credentials belonging to a user and evaluate using user's primary role
         *
         * @generated from rpc Genesis.LoginService.UserLoginPrimary
         */
        userLoginPrimary: ***REMOVED***
            name: "UserLoginPrimary",
            I: logins_pb_js_1.UserLoginRequest,
            O: logins_pb_js_1.UserLoginResponse,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * Check if the auth token is still valid
         *
         * @generated from rpc Genesis.LoginService.IsAuthTokenValid
         */
        isAuthTokenValid: ***REMOVED***
            name: "IsAuthTokenValid",
            I: logins_pb_js_1.AuthTokenValidityRequest,
            O: base_pb_js_1.BooleanResponse,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
        /**
         * Logout
         *
         * @generated from rpc Genesis.LoginService.Logout
         */
        logout: ***REMOVED***
            name: "Logout",
            I: logins_pb_js_1.LogoutRequest,
            O: logins_pb_js_1.LogoutResponse,
            kind: protobuf_1.MethodKind.Unary,
    ***REMOVED***
***REMOVED***
***REMOVED***;
