// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=ts"
// @generated from file equations_sales_bundles.proto (package Genesis, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import ***REMOVED*** EquationSalesBundle, EquationSalesBundleItem, EquationSalesBundleItemHistoryRequest, EquationsSalesBundlesItemsList, EquationsSalesBundlesList, EquationsSalesBundlesServiceCreateRequest, EquationsSalesBundlesServiceEntityPaginationReq, EquationsSalesBundlesServiceFilterReq, EquationsSalesBundlesServiceItemCreateRequest, EquationsSalesBundlesServiceItemUpdateRequest, EquationsSalesBundlesServicePaginationReq, EquationsSalesBundlesServicePaginationResponse, EquationsSalesBundlesServiceSearchAllReq, EquationsSalesBundlesServiceUpdateRequest ***REMOVED*** from "./equations_sales_bundles_pb.js";
import ***REMOVED*** ActiveStatus, CloneRequest, CountInSLCStatusRequest, CountResponse, Identifier, IdentifierUUID, IdentifierWithSearchKey, IdentifierWithUserComment, ReorderItemsRequest ***REMOVED*** from "./base_pb.js";
import ***REMOVED*** MethodKind ***REMOVED*** from "@bufbuild/protobuf";

/**
 *
 * Describes the common methods applicable on each equation sales bundle
 *
 * @generated from service Genesis.EquationsSalesBundlesService
 */
export const EquationsSalesBundlesService = ***REMOVED***
  typeName: "Genesis.EquationsSalesBundlesService",
  methods: ***REMOVED***
    /**
     * Create and send for verification
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.Create
     */
    create: ***REMOVED***
      name: "Create",
      I: EquationsSalesBundlesServiceCreateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Create and save as draft
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.Draft
     */
    draft: ***REMOVED***
      name: "Draft",
      I: EquationsSalesBundlesServiceCreateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Update draft
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.DraftUpdate
     */
    draftUpdate: ***REMOVED***
      name: "DraftUpdate",
      I: EquationsSalesBundlesServiceUpdateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Send for verification
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.SendForVerification
     */
    sendForVerification: ***REMOVED***
      name: "SendForVerification",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Verify
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.Verify
     */
    verify: ***REMOVED***
      name: "Verify",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Approve
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.Approve
     */
    approve: ***REMOVED***
      name: "Approve",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Send For Revision
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.SendForRevision
     */
    sendForRevision: ***REMOVED***
      name: "SendForRevision",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Update revision
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.RevisionUpdate
     */
    revisionUpdate: ***REMOVED***
      name: "RevisionUpdate",
      I: EquationsSalesBundlesServiceUpdateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Halt
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.Halt
     */
    halt: ***REMOVED***
      name: "Halt",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Discard
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.Discard
     */
    discard: ***REMOVED***
      name: "Discard",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Restore
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.Restore
     */
    restore: ***REMOVED***
      name: "Restore",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Complete
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.Complete
     */
    complete: ***REMOVED***
      name: "Complete",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Repeat
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.Repeat
     */
    repeat: ***REMOVED***
      name: "Repeat",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Reopen
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.Reopen
     */
    reopen: ***REMOVED***
      name: "Reopen",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Add comment
     *
     * Send Email
     * rpc SendEmail (IdentifierWithEmailAttributes) returns (Identifier);
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.CommentAdd
     */
    commentAdd: ***REMOVED***
      name: "CommentAdd",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Clone equation from an existing equation (denoted by the identifier)
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.Clone
     */
    clone: ***REMOVED***
      name: "Clone",
      I: CloneRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Add an item to a equation sales bundle
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.AddEquationSalesBundleItem
     */
    addEquationSalesBundleItem: ***REMOVED***
      name: "AddEquationSalesBundleItem",
      I: EquationsSalesBundlesServiceItemCreateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Modify an item in a equation sales bundle
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.ModifyEquationSalesBundleItem
     */
    modifyEquationSalesBundleItem: ***REMOVED***
      name: "ModifyEquationSalesBundleItem",
      I: EquationsSalesBundlesServiceItemUpdateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Approve an item in a equation sales bundle
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.ApproveEquationSalesBundleItem
     */
    approveEquationSalesBundleItem: ***REMOVED***
      name: "ApproveEquationSalesBundleItem",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Delete an item in a equation sales bundle
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.DeleteEquationSalesBundleItem
     */
    deleteEquationSalesBundleItem: ***REMOVED***
      name: "DeleteEquationSalesBundleItem",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Reorder items in a equation sales bundle
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.ReorderEquationSalesBundleItems
     */
    reorderEquationSalesBundleItems: ***REMOVED***
      name: "ReorderEquationSalesBundleItems",
      I: ReorderItemsRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View Equation Sales Bundle Item by ID
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.ViewEquationSalesBundleItemByID
     */
    viewEquationSalesBundleItemByID: ***REMOVED***
      name: "ViewEquationSalesBundleItemByID",
      I: Identifier,
      O: EquationSalesBundleItem,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View approved equation sales bundle items for given equation sales bundle ID
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.ViewApprovedEquationSalesBundleItems
     */
    viewApprovedEquationSalesBundleItems: ***REMOVED***
      name: "ViewApprovedEquationSalesBundleItems",
      I: IdentifierWithSearchKey,
      O: EquationsSalesBundlesItemsList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View unapproved equation sales bundle items for given equation sales bundle ID
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.ViewUnapprovedEquationSalesBundleItems
     */
    viewUnapprovedEquationSalesBundleItems: ***REMOVED***
      name: "ViewUnapprovedEquationSalesBundleItems",
      I: IdentifierWithSearchKey,
      O: EquationsSalesBundlesItemsList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View the history of the equation sales bundle item
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.ViewEquationSalesBundleItemHistory
     */
    viewEquationSalesBundleItemHistory: ***REMOVED***
      name: "ViewEquationSalesBundleItemHistory",
      I: EquationSalesBundleItemHistoryRequest,
      O: EquationsSalesBundlesItemsList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View by ID
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.ViewByID
     */
    viewByID: ***REMOVED***
      name: "ViewByID",
      I: Identifier,
      O: EquationSalesBundle,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View all
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.ViewAll
     */
    viewAll: ***REMOVED***
      name: "ViewAll",
      I: ActiveStatus,
      O: EquationsSalesBundlesList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View all with the given entity UUID
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.ViewAllForEntityUUID
     */
    viewAllForEntityUUID: ***REMOVED***
      name: "ViewAllForEntityUUID",
      I: IdentifierUUID,
      O: EquationsSalesBundlesList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View with pagination
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.ViewWithPagination
     */
    viewWithPagination: ***REMOVED***
      name: "ViewWithPagination",
      I: EquationsSalesBundlesServicePaginationReq,
      O: EquationsSalesBundlesServicePaginationResponse,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View with pagination with the given entity UUID
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.ViewWithPaginationForEntityUUID
     */
    viewWithPaginationForEntityUUID: ***REMOVED***
      name: "ViewWithPaginationForEntityUUID",
      I: EquationsSalesBundlesServiceEntityPaginationReq,
      O: EquationsSalesBundlesServicePaginationResponse,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View the latest equation for a family (denoted by the given identifier)
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.ViewForFamilyID
     */
    viewForFamilyID: ***REMOVED***
      name: "ViewForFamilyID",
      I: Identifier,
      O: EquationSalesBundle,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View all that match the given search key
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.SearchAll
     */
    searchAll: ***REMOVED***
      name: "SearchAll",
      I: EquationsSalesBundlesServiceSearchAllReq,
      O: EquationsSalesBundlesList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View all that match the given filter criteria
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.Filter
     */
    filter: ***REMOVED***
      name: "Filter",
      I: EquationsSalesBundlesServiceFilterReq,
      O: EquationsSalesBundlesList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Count in status
     *
     * @generated from rpc Genesis.EquationsSalesBundlesService.CountInStatus
     */
    countInStatus: ***REMOVED***
      name: "CountInStatus",
      I: CountInSLCStatusRequest,
      O: CountResponse,
      kind: MethodKind.Unary,
***REMOVED***
  ***REMOVED***
***REMOVED*** as const;

