// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=ts"
// @generated from file goods_receipts.proto (package Genesis, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GoodsReceipt, GoodsReceiptItem, GoodsReceiptItemHistoryRequest, GoodsReceiptItemProspectiveInfoRequest, GoodsReceiptsItemsList, GoodsReceiptsList, GoodsReceiptsServiceAlreadyAddedQuantityForSourceRequest, GoodsReceiptsServiceAutofillRequest, GoodsReceiptsServiceCreateRequest, GoodsReceiptsServiceEntityPaginationReq, GoodsReceiptsServiceFilterReq, GoodsReceiptsServiceItemCreateRequest, GoodsReceiptsServiceItemUpdateRequest, GoodsReceiptsServicePaginationReq, GoodsReceiptsServicePaginationResponse, GoodsReceiptsServiceSearchAllReq, GoodsReceiptsServiceUpdateRequest } from "./goods_receipts_pb.js";
import { ActiveStatus, BooleanResponse, CountInSLCStatusRequest, CountResponse, DualQuantitiesResponse, Identifier, IdentifierUUID, IdentifierWithEmailAttributes, IdentifierWithSearchKey, IdentifierWithUserComment, ReorderItemsRequest } from "./base_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { FamiliesList } from "./families_pb.js";

/**
 *
 * Describes the common methods applicable on each goods receipt
 *
 * @generated from service Genesis.GoodsReceiptsService
 */
export const GoodsReceiptsService = {
  typeName: "Genesis.GoodsReceiptsService",
  methods: {
    /**
     * Create and send for verification
     *
     * @generated from rpc Genesis.GoodsReceiptsService.Create
     */
    create: {
      name: "Create",
      I: GoodsReceiptsServiceCreateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Create and save as draft
     *
     * @generated from rpc Genesis.GoodsReceiptsService.Draft
     */
    draft: {
      name: "Draft",
      I: GoodsReceiptsServiceCreateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Update draft
     *
     * @generated from rpc Genesis.GoodsReceiptsService.DraftUpdate
     */
    draftUpdate: {
      name: "DraftUpdate",
      I: GoodsReceiptsServiceUpdateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Send for verification
     *
     * @generated from rpc Genesis.GoodsReceiptsService.SendForVerification
     */
    sendForVerification: {
      name: "SendForVerification",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Verify
     *
     * @generated from rpc Genesis.GoodsReceiptsService.Verify
     */
    verify: {
      name: "Verify",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Approve
     *
     * @generated from rpc Genesis.GoodsReceiptsService.Approve
     */
    approve: {
      name: "Approve",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Send For Revision
     *
     * @generated from rpc Genesis.GoodsReceiptsService.SendForRevision
     */
    sendForRevision: {
      name: "SendForRevision",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Update revision
     *
     * @generated from rpc Genesis.GoodsReceiptsService.RevisionUpdate
     */
    revisionUpdate: {
      name: "RevisionUpdate",
      I: GoodsReceiptsServiceUpdateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Halt
     *
     * @generated from rpc Genesis.GoodsReceiptsService.Halt
     */
    halt: {
      name: "Halt",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Discard
     *
     * @generated from rpc Genesis.GoodsReceiptsService.Discard
     */
    discard: {
      name: "Discard",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Restore
     *
     * @generated from rpc Genesis.GoodsReceiptsService.Restore
     */
    restore: {
      name: "Restore",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Complete
     *
     * @generated from rpc Genesis.GoodsReceiptsService.Complete
     */
    complete: {
      name: "Complete",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Repeat
     *
     * @generated from rpc Genesis.GoodsReceiptsService.Repeat
     */
    repeat: {
      name: "Repeat",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Reopen
     *
     * @generated from rpc Genesis.GoodsReceiptsService.Reopen
     */
    reopen: {
      name: "Reopen",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Add comment
     *
     * @generated from rpc Genesis.GoodsReceiptsService.CommentAdd
     */
    commentAdd: {
      name: "CommentAdd",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Send Email
     *
     * @generated from rpc Genesis.GoodsReceiptsService.SendEmail
     */
    sendEmail: {
      name: "SendEmail",
      I: IdentifierWithEmailAttributes,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Autofill the goods receipt
     *
     * @generated from rpc Genesis.GoodsReceiptsService.Autofill
     */
    autofill: {
      name: "Autofill",
      I: GoodsReceiptsServiceAutofillRequest,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Checks if the Goods Receipt can be marked as completed
     *
     * @generated from rpc Genesis.GoodsReceiptsService.IsCompletable
     */
    isCompletable: {
      name: "IsCompletable",
      I: Identifier,
      O: BooleanResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Add an item to a goods receipt
     *
     * @generated from rpc Genesis.GoodsReceiptsService.AddGoodsReceiptItem
     */
    addGoodsReceiptItem: {
      name: "AddGoodsReceiptItem",
      I: GoodsReceiptsServiceItemCreateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Modify an item in a goods receipt
     *
     * @generated from rpc Genesis.GoodsReceiptsService.ModifyGoodsReceiptItem
     */
    modifyGoodsReceiptItem: {
      name: "ModifyGoodsReceiptItem",
      I: GoodsReceiptsServiceItemUpdateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Approve an item in a goods receipt
     *
     * @generated from rpc Genesis.GoodsReceiptsService.ApproveGoodsReceiptItem
     */
    approveGoodsReceiptItem: {
      name: "ApproveGoodsReceiptItem",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Delete an item in a goods receipt
     *
     * @generated from rpc Genesis.GoodsReceiptsService.DeleteGoodsReceiptItem
     */
    deleteGoodsReceiptItem: {
      name: "DeleteGoodsReceiptItem",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Reorder items in a goods receipt
     *
     * @generated from rpc Genesis.GoodsReceiptsService.ReorderGoodsReceiptItems
     */
    reorderGoodsReceiptItems: {
      name: "ReorderGoodsReceiptItems",
      I: ReorderItemsRequest,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * View Goods Receipt Item by ID
     *
     * @generated from rpc Genesis.GoodsReceiptsService.ViewGoodsReceiptItemByID
     */
    viewGoodsReceiptItemByID: {
      name: "ViewGoodsReceiptItemByID",
      I: Identifier,
      O: GoodsReceiptItem,
      kind: MethodKind.Unary,
    },
    /**
     * View approved goods receipt items for given goods receipt ID
     *
     * @generated from rpc Genesis.GoodsReceiptsService.ViewApprovedGoodsReceiptItems
     */
    viewApprovedGoodsReceiptItems: {
      name: "ViewApprovedGoodsReceiptItems",
      I: IdentifierWithSearchKey,
      O: GoodsReceiptsItemsList,
      kind: MethodKind.Unary,
    },
    /**
     * View unapproved goods receipt items for given goods receipt ID
     *
     * @generated from rpc Genesis.GoodsReceiptsService.ViewUnapprovedGoodsReceiptItems
     */
    viewUnapprovedGoodsReceiptItems: {
      name: "ViewUnapprovedGoodsReceiptItems",
      I: IdentifierWithSearchKey,
      O: GoodsReceiptsItemsList,
      kind: MethodKind.Unary,
    },
    /**
     * View the history of the goods receipt item
     *
     * @generated from rpc Genesis.GoodsReceiptsService.ViewGoodsReceiptItemHistory
     */
    viewGoodsReceiptItemHistory: {
      name: "ViewGoodsReceiptItemHistory",
      I: GoodsReceiptItemHistoryRequest,
      O: GoodsReceiptsItemsList,
      kind: MethodKind.Unary,
    },
    /**
     * View by ID
     *
     * @generated from rpc Genesis.GoodsReceiptsService.ViewByID
     */
    viewByID: {
      name: "ViewByID",
      I: Identifier,
      O: GoodsReceipt,
      kind: MethodKind.Unary,
    },
    /**
     * View all
     *
     * @generated from rpc Genesis.GoodsReceiptsService.ViewAll
     */
    viewAll: {
      name: "ViewAll",
      I: ActiveStatus,
      O: GoodsReceiptsList,
      kind: MethodKind.Unary,
    },
    /**
     * View all with the given entity UUID
     *
     * @generated from rpc Genesis.GoodsReceiptsService.ViewAllForEntityUUID
     */
    viewAllForEntityUUID: {
      name: "ViewAllForEntityUUID",
      I: IdentifierUUID,
      O: GoodsReceiptsList,
      kind: MethodKind.Unary,
    },
    /**
     * View with pagination
     *
     * @generated from rpc Genesis.GoodsReceiptsService.ViewWithPagination
     */
    viewWithPagination: {
      name: "ViewWithPagination",
      I: GoodsReceiptsServicePaginationReq,
      O: GoodsReceiptsServicePaginationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * View with pagination with the given entity UUID
     *
     * @generated from rpc Genesis.GoodsReceiptsService.ViewWithPaginationForEntityUUID
     */
    viewWithPaginationForEntityUUID: {
      name: "ViewWithPaginationForEntityUUID",
      I: GoodsReceiptsServiceEntityPaginationReq,
      O: GoodsReceiptsServicePaginationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * View prospective families for the given goods receipt
     *
     * @generated from rpc Genesis.GoodsReceiptsService.ViewProspectiveFamilies
     */
    viewProspectiveFamilies: {
      name: "ViewProspectiveFamilies",
      I: IdentifierWithSearchKey,
      O: FamiliesList,
      kind: MethodKind.Unary,
    },
    /**
     * View prospective goods receipt item info for the given family ID and goods receipt ID
     *
     * @generated from rpc Genesis.GoodsReceiptsService.ViewProspectiveGoodsReceiptItem
     */
    viewProspectiveGoodsReceiptItem: {
      name: "ViewProspectiveGoodsReceiptItem",
      I: GoodsReceiptItemProspectiveInfoRequest,
      O: GoodsReceiptsServiceItemCreateRequest,
      kind: MethodKind.Unary,
    },
    /**
     * View the associated vendor invoice ID that is denoted by the identifier in the response for the goods receipt that is denoted by the identifier in the request
     *
     * @generated from rpc Genesis.GoodsReceiptsService.ViewAssociatedVendorInvoiceID
     */
    viewAssociatedVendorInvoiceID: {
      name: "ViewAssociatedVendorInvoiceID",
      I: Identifier,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Checks if the Goods Receipt has been billed
     *
     * @generated from rpc Genesis.GoodsReceiptsService.IsBilled
     */
    isBilled: {
      name: "IsBilled",
      I: Identifier,
      O: BooleanResponse,
      kind: MethodKind.Unary,
    },
    /**
     * View already added quantities
     *
     * @generated from rpc Genesis.GoodsReceiptsService.ViewAddedFamilyQuantityForSource
     */
    viewAddedFamilyQuantityForSource: {
      name: "ViewAddedFamilyQuantityForSource",
      I: GoodsReceiptsServiceAlreadyAddedQuantityForSourceRequest,
      O: DualQuantitiesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * View all that match the given search key
     *
     * @generated from rpc Genesis.GoodsReceiptsService.SearchAll
     */
    searchAll: {
      name: "SearchAll",
      I: GoodsReceiptsServiceSearchAllReq,
      O: GoodsReceiptsList,
      kind: MethodKind.Unary,
    },
    /**
     * View all that match the given filter criteria
     *
     * @generated from rpc Genesis.GoodsReceiptsService.Filter
     */
    filter: {
      name: "Filter",
      I: GoodsReceiptsServiceFilterReq,
      O: GoodsReceiptsList,
      kind: MethodKind.Unary,
    },
    /**
     * Count in status
     *
     * @generated from rpc Genesis.GoodsReceiptsService.CountInStatus
     */
    countInStatus: {
      name: "CountInStatus",
      I: CountInSLCStatusRequest,
      O: CountResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

