// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=ts"
// @generated from file production_plans.proto (package Genesis, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import ***REMOVED*** ProductionPlan, ProductionPlanItem, ProductionPlanItemHistoryRequest, ProductionPlanItemProspectiveInfoRequest, ProductionPlansItemsList, ProductionPlansList, ProductionPlansServiceAutofillRequest, ProductionPlansServiceCreateRequest, ProductionPlansServiceEntityPaginationReq, ProductionPlansServiceFilterReq, ProductionPlansServiceItemCreateRequest, ProductionPlansServiceItemUpdateRequest, ProductionPlansServicePaginationReq, ProductionPlansServicePaginationResponse, ProductionPlansServiceSearchAllReq, ProductionPlansServiceUpdateRequest ***REMOVED*** from "./production_plans_pb.js";
import ***REMOVED*** ActiveStatus, BooleanResponse, CountInSLCStatusRequest, CountResponse, Identifier, IdentifierUUID, IdentifierWithEmailAttributes, IdentifierWithSearchKey, IdentifierWithUserComment, ReorderItemsRequest ***REMOVED*** from "./base_pb.js";
import ***REMOVED*** MethodKind ***REMOVED*** from "@bufbuild/protobuf";
import ***REMOVED*** FamiliesList ***REMOVED*** from "./families_pb.js";

/**
 *
 * Describes the common methods applicable on each production plan
 *
 * @generated from service Genesis.ProductionPlansService
 */
export const ProductionPlansService = ***REMOVED***
  typeName: "Genesis.ProductionPlansService",
  methods: ***REMOVED***
    /**
     * Create and send for verification
     *
     * @generated from rpc Genesis.ProductionPlansService.Create
     */
    create: ***REMOVED***
      name: "Create",
      I: ProductionPlansServiceCreateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Create and save as draft
     *
     * @generated from rpc Genesis.ProductionPlansService.Draft
     */
    draft: ***REMOVED***
      name: "Draft",
      I: ProductionPlansServiceCreateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Update draft
     *
     * @generated from rpc Genesis.ProductionPlansService.DraftUpdate
     */
    draftUpdate: ***REMOVED***
      name: "DraftUpdate",
      I: ProductionPlansServiceUpdateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Send for verification
     *
     * @generated from rpc Genesis.ProductionPlansService.SendForVerification
     */
    sendForVerification: ***REMOVED***
      name: "SendForVerification",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Verify
     *
     * @generated from rpc Genesis.ProductionPlansService.Verify
     */
    verify: ***REMOVED***
      name: "Verify",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Approve
     *
     * @generated from rpc Genesis.ProductionPlansService.Approve
     */
    approve: ***REMOVED***
      name: "Approve",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Send For Revision
     *
     * @generated from rpc Genesis.ProductionPlansService.SendForRevision
     */
    sendForRevision: ***REMOVED***
      name: "SendForRevision",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Update revision
     *
     * @generated from rpc Genesis.ProductionPlansService.RevisionUpdate
     */
    revisionUpdate: ***REMOVED***
      name: "RevisionUpdate",
      I: ProductionPlansServiceUpdateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Halt
     *
     * @generated from rpc Genesis.ProductionPlansService.Halt
     */
    halt: ***REMOVED***
      name: "Halt",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Discard
     *
     * @generated from rpc Genesis.ProductionPlansService.Discard
     */
    discard: ***REMOVED***
      name: "Discard",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Restore
     *
     * @generated from rpc Genesis.ProductionPlansService.Restore
     */
    restore: ***REMOVED***
      name: "Restore",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Complete
     *
     * @generated from rpc Genesis.ProductionPlansService.Complete
     */
    complete: ***REMOVED***
      name: "Complete",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Repeat
     *
     * @generated from rpc Genesis.ProductionPlansService.Repeat
     */
    repeat: ***REMOVED***
      name: "Repeat",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Reopen
     *
     * @generated from rpc Genesis.ProductionPlansService.Reopen
     */
    reopen: ***REMOVED***
      name: "Reopen",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Add comment
     *
     * @generated from rpc Genesis.ProductionPlansService.CommentAdd
     */
    commentAdd: ***REMOVED***
      name: "CommentAdd",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Send Email
     *
     * @generated from rpc Genesis.ProductionPlansService.SendEmail
     */
    sendEmail: ***REMOVED***
      name: "SendEmail",
      I: IdentifierWithEmailAttributes,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Autofill the production plan
     *
     * @generated from rpc Genesis.ProductionPlansService.Autofill
     */
    autofill: ***REMOVED***
      name: "Autofill",
      I: ProductionPlansServiceAutofillRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Checks if the Production Plan can be marked as completed
     *
     * @generated from rpc Genesis.ProductionPlansService.IsCompletable
     */
    isCompletable: ***REMOVED***
      name: "IsCompletable",
      I: Identifier,
      O: BooleanResponse,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Add an item to a production plan
     *
     * @generated from rpc Genesis.ProductionPlansService.AddProductionPlanItem
     */
    addProductionPlanItem: ***REMOVED***
      name: "AddProductionPlanItem",
      I: ProductionPlansServiceItemCreateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Modify an item in a production plan
     *
     * @generated from rpc Genesis.ProductionPlansService.ModifyProductionPlanItem
     */
    modifyProductionPlanItem: ***REMOVED***
      name: "ModifyProductionPlanItem",
      I: ProductionPlansServiceItemUpdateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Approve an item in a production plan
     *
     * @generated from rpc Genesis.ProductionPlansService.ApproveProductionPlanItem
     */
    approveProductionPlanItem: ***REMOVED***
      name: "ApproveProductionPlanItem",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Delete an item in a production plan
     *
     * @generated from rpc Genesis.ProductionPlansService.DeleteProductionPlanItem
     */
    deleteProductionPlanItem: ***REMOVED***
      name: "DeleteProductionPlanItem",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Reorder items in a production plan
     *
     * @generated from rpc Genesis.ProductionPlansService.ReorderProductionPlanItems
     */
    reorderProductionPlanItems: ***REMOVED***
      name: "ReorderProductionPlanItems",
      I: ReorderItemsRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View Production Plan Item by ID
     *
     * @generated from rpc Genesis.ProductionPlansService.ViewProductionPlanItemByID
     */
    viewProductionPlanItemByID: ***REMOVED***
      name: "ViewProductionPlanItemByID",
      I: Identifier,
      O: ProductionPlanItem,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View approved production plan items for given production plan ID
     *
     * @generated from rpc Genesis.ProductionPlansService.ViewApprovedProductionPlanItems
     */
    viewApprovedProductionPlanItems: ***REMOVED***
      name: "ViewApprovedProductionPlanItems",
      I: IdentifierWithSearchKey,
      O: ProductionPlansItemsList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View unapproved production plan items for given production plan ID
     *
     * @generated from rpc Genesis.ProductionPlansService.ViewUnapprovedProductionPlanItems
     */
    viewUnapprovedProductionPlanItems: ***REMOVED***
      name: "ViewUnapprovedProductionPlanItems",
      I: IdentifierWithSearchKey,
      O: ProductionPlansItemsList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View the history of the production plan item
     *
     * @generated from rpc Genesis.ProductionPlansService.ViewProductionPlanItemHistory
     */
    viewProductionPlanItemHistory: ***REMOVED***
      name: "ViewProductionPlanItemHistory",
      I: ProductionPlanItemHistoryRequest,
      O: ProductionPlansItemsList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View by ID
     *
     * @generated from rpc Genesis.ProductionPlansService.ViewByID
     */
    viewByID: ***REMOVED***
      name: "ViewByID",
      I: Identifier,
      O: ProductionPlan,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View all
     *
     * @generated from rpc Genesis.ProductionPlansService.ViewAll
     */
    viewAll: ***REMOVED***
      name: "ViewAll",
      I: ActiveStatus,
      O: ProductionPlansList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View all with the given entity UUID
     *
     * @generated from rpc Genesis.ProductionPlansService.ViewAllForEntityUUID
     */
    viewAllForEntityUUID: ***REMOVED***
      name: "ViewAllForEntityUUID",
      I: IdentifierUUID,
      O: ProductionPlansList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View with pagination
     *
     * @generated from rpc Genesis.ProductionPlansService.ViewWithPagination
     */
    viewWithPagination: ***REMOVED***
      name: "ViewWithPagination",
      I: ProductionPlansServicePaginationReq,
      O: ProductionPlansServicePaginationResponse,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View with pagination with the given entity UUID
     *
     * @generated from rpc Genesis.ProductionPlansService.ViewWithPaginationForEntityUUID
     */
    viewWithPaginationForEntityUUID: ***REMOVED***
      name: "ViewWithPaginationForEntityUUID",
      I: ProductionPlansServiceEntityPaginationReq,
      O: ProductionPlansServicePaginationResponse,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View prospective families for the given production plan
     *
     * @generated from rpc Genesis.ProductionPlansService.ViewProspectiveFamilies
     */
    viewProspectiveFamilies: ***REMOVED***
      name: "ViewProspectiveFamilies",
      I: IdentifierWithSearchKey,
      O: FamiliesList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View prospective production plan item info for the given family ID and production plan ID
     *
     * @generated from rpc Genesis.ProductionPlansService.ViewProspectiveProductionPlanItem
     */
    viewProspectiveProductionPlanItem: ***REMOVED***
      name: "ViewProspectiveProductionPlanItem",
      I: ProductionPlanItemProspectiveInfoRequest,
      O: ProductionPlansServiceItemCreateRequest,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View all that match the given search key
     *
     * @generated from rpc Genesis.ProductionPlansService.SearchAll
     */
    searchAll: ***REMOVED***
      name: "SearchAll",
      I: ProductionPlansServiceSearchAllReq,
      O: ProductionPlansList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View all that match the given filter criteria
     *
     * @generated from rpc Genesis.ProductionPlansService.Filter
     */
    filter: ***REMOVED***
      name: "Filter",
      I: ProductionPlansServiceFilterReq,
      O: ProductionPlansList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Count in status
     *
     * @generated from rpc Genesis.ProductionPlansService.CountInStatus
     */
    countInStatus: ***REMOVED***
      name: "CountInStatus",
      I: CountInSLCStatusRequest,
      O: CountResponse,
      kind: MethodKind.Unary,
***REMOVED***
  ***REMOVED***
***REMOVED*** as const;

