// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=ts"
// @generated from file quotations_requests.proto (package Genesis, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import ***REMOVED*** QuotationRequest, QuotationRequestItem, QuotationRequestItemHistoryRequest, QuotationsRequestsItemsList, QuotationsRequestsList, QuotationsRequestsServiceAutofillRequest, QuotationsRequestsServiceCreateRequest, QuotationsRequestsServiceEntityPaginationReq, QuotationsRequestsServiceFilterReq, QuotationsRequestsServiceItemCreateRequest, QuotationsRequestsServiceItemUpdateRequest, QuotationsRequestsServicePaginationReq, QuotationsRequestsServicePaginationResponse, QuotationsRequestsServiceSearchAllReq, QuotationsRequestsServiceUpdateRequest ***REMOVED*** from "./quotations_requests_pb.js";
import ***REMOVED*** ActiveStatus, CountInSLCStatusRequest, CountResponse, Identifier, IdentifierUUID, IdentifierWithSearchKey, IdentifierWithUserComment, ReorderItemsRequest ***REMOVED*** from "./base_pb.js";
import ***REMOVED*** MethodKind ***REMOVED*** from "@bufbuild/protobuf";

/**
 *
 * Describes the common methods applicable on each quotation request
 *
 * @generated from service Genesis.QuotationsRequestsService
 */
export const QuotationsRequestsService = ***REMOVED***
  typeName: "Genesis.QuotationsRequestsService",
  methods: ***REMOVED***
    /**
     * Create and send for verification
     *
     * @generated from rpc Genesis.QuotationsRequestsService.Create
     */
    create: ***REMOVED***
      name: "Create",
      I: QuotationsRequestsServiceCreateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Create and save as draft
     *
     * @generated from rpc Genesis.QuotationsRequestsService.Draft
     */
    draft: ***REMOVED***
      name: "Draft",
      I: QuotationsRequestsServiceCreateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Update draft
     *
     * @generated from rpc Genesis.QuotationsRequestsService.DraftUpdate
     */
    draftUpdate: ***REMOVED***
      name: "DraftUpdate",
      I: QuotationsRequestsServiceUpdateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Send for verification
     *
     * @generated from rpc Genesis.QuotationsRequestsService.SendForVerification
     */
    sendForVerification: ***REMOVED***
      name: "SendForVerification",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Verify
     *
     * @generated from rpc Genesis.QuotationsRequestsService.Verify
     */
    verify: ***REMOVED***
      name: "Verify",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Approve
     *
     * @generated from rpc Genesis.QuotationsRequestsService.Approve
     */
    approve: ***REMOVED***
      name: "Approve",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Send For Revision
     *
     * @generated from rpc Genesis.QuotationsRequestsService.SendForRevision
     */
    sendForRevision: ***REMOVED***
      name: "SendForRevision",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Update revision
     *
     * @generated from rpc Genesis.QuotationsRequestsService.RevisionUpdate
     */
    revisionUpdate: ***REMOVED***
      name: "RevisionUpdate",
      I: QuotationsRequestsServiceUpdateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Halt
     *
     * @generated from rpc Genesis.QuotationsRequestsService.Halt
     */
    halt: ***REMOVED***
      name: "Halt",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Discard
     *
     * @generated from rpc Genesis.QuotationsRequestsService.Discard
     */
    discard: ***REMOVED***
      name: "Discard",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Restore
     *
     * @generated from rpc Genesis.QuotationsRequestsService.Restore
     */
    restore: ***REMOVED***
      name: "Restore",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Complete
     *
     * @generated from rpc Genesis.QuotationsRequestsService.Complete
     */
    complete: ***REMOVED***
      name: "Complete",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Repeat
     *
     * @generated from rpc Genesis.QuotationsRequestsService.Repeat
     */
    repeat: ***REMOVED***
      name: "Repeat",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Reopen
     *
     * @generated from rpc Genesis.QuotationsRequestsService.Reopen
     */
    reopen: ***REMOVED***
      name: "Reopen",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Add comment
     *
     * @generated from rpc Genesis.QuotationsRequestsService.CommentAdd
     */
    commentAdd: ***REMOVED***
      name: "CommentAdd",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Autofill the quotation request (from the associated purchase enquiry)
     *
     * @generated from rpc Genesis.QuotationsRequestsService.Autofill
     */
    autofill: ***REMOVED***
      name: "Autofill",
      I: QuotationsRequestsServiceAutofillRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Add an item to a quotation request
     *
     * @generated from rpc Genesis.QuotationsRequestsService.AddQuotationRequestItem
     */
    addQuotationRequestItem: ***REMOVED***
      name: "AddQuotationRequestItem",
      I: QuotationsRequestsServiceItemCreateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Modify an item in a quotation request
     *
     * @generated from rpc Genesis.QuotationsRequestsService.ModifyQuotationRequestItem
     */
    modifyQuotationRequestItem: ***REMOVED***
      name: "ModifyQuotationRequestItem",
      I: QuotationsRequestsServiceItemUpdateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Approve an item in a quotation request
     *
     * @generated from rpc Genesis.QuotationsRequestsService.ApproveQuotationRequestItem
     */
    approveQuotationRequestItem: ***REMOVED***
      name: "ApproveQuotationRequestItem",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Delete an item in a quotation request
     *
     * @generated from rpc Genesis.QuotationsRequestsService.DeleteQuotationRequestItem
     */
    deleteQuotationRequestItem: ***REMOVED***
      name: "DeleteQuotationRequestItem",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Reorder items in a quotation request
     *
     * @generated from rpc Genesis.QuotationsRequestsService.ReorderQuotationRequestItems
     */
    reorderQuotationRequestItems: ***REMOVED***
      name: "ReorderQuotationRequestItems",
      I: ReorderItemsRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View quotation request Item by ID
     *
     * @generated from rpc Genesis.QuotationsRequestsService.ViewQuotationRequestItemByID
     */
    viewQuotationRequestItemByID: ***REMOVED***
      name: "ViewQuotationRequestItemByID",
      I: Identifier,
      O: QuotationRequestItem,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View approved quotation request items for given quotation request ID
     *
     * @generated from rpc Genesis.QuotationsRequestsService.ViewApprovedQuotationRequestItems
     */
    viewApprovedQuotationRequestItems: ***REMOVED***
      name: "ViewApprovedQuotationRequestItems",
      I: IdentifierWithSearchKey,
      O: QuotationsRequestsItemsList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View unapproved quotation request items for given quotation request ID
     *
     * @generated from rpc Genesis.QuotationsRequestsService.ViewUnapprovedQuotationRequestItems
     */
    viewUnapprovedQuotationRequestItems: ***REMOVED***
      name: "ViewUnapprovedQuotationRequestItems",
      I: IdentifierWithSearchKey,
      O: QuotationsRequestsItemsList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View the history of the quotation request item
     *
     * @generated from rpc Genesis.QuotationsRequestsService.ViewQuotationRequestItemHistory
     */
    viewQuotationRequestItemHistory: ***REMOVED***
      name: "ViewQuotationRequestItemHistory",
      I: QuotationRequestItemHistoryRequest,
      O: QuotationsRequestsItemsList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View by ID
     *
     * @generated from rpc Genesis.QuotationsRequestsService.ViewByID
     */
    viewByID: ***REMOVED***
      name: "ViewByID",
      I: Identifier,
      O: QuotationRequest,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View all
     *
     * @generated from rpc Genesis.QuotationsRequestsService.ViewAll
     */
    viewAll: ***REMOVED***
      name: "ViewAll",
      I: ActiveStatus,
      O: QuotationsRequestsList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View all with the given entity UUID
     *
     * @generated from rpc Genesis.QuotationsRequestsService.ViewAllForEntityUUID
     */
    viewAllForEntityUUID: ***REMOVED***
      name: "ViewAllForEntityUUID",
      I: IdentifierUUID,
      O: QuotationsRequestsList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View with pagination
     *
     * @generated from rpc Genesis.QuotationsRequestsService.ViewWithPagination
     */
    viewWithPagination: ***REMOVED***
      name: "ViewWithPagination",
      I: QuotationsRequestsServicePaginationReq,
      O: QuotationsRequestsServicePaginationResponse,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View with pagination with the given entity UUID
     *
     * @generated from rpc Genesis.QuotationsRequestsService.ViewWithPaginationForEntityUUID
     */
    viewWithPaginationForEntityUUID: ***REMOVED***
      name: "ViewWithPaginationForEntityUUID",
      I: QuotationsRequestsServiceEntityPaginationReq,
      O: QuotationsRequestsServicePaginationResponse,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View all that match the given search key
     *
     * @generated from rpc Genesis.QuotationsRequestsService.SearchAll
     */
    searchAll: ***REMOVED***
      name: "SearchAll",
      I: QuotationsRequestsServiceSearchAllReq,
      O: QuotationsRequestsList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View all that match the given filter criteria
     *
     * @generated from rpc Genesis.QuotationsRequestsService.Filter
     */
    filter: ***REMOVED***
      name: "Filter",
      I: QuotationsRequestsServiceFilterReq,
      O: QuotationsRequestsList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Count in status
     *
     * @generated from rpc Genesis.QuotationsRequestsService.CountInStatus
     */
    countInStatus: ***REMOVED***
      name: "CountInStatus",
      I: CountInSLCStatusRequest,
      O: CountResponse,
      kind: MethodKind.Unary,
***REMOVED***
  ***REMOVED***
***REMOVED*** as const;

