// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=ts"
// @generated from file skills_groups.proto (package Genesis, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import ***REMOVED*** SkillGroup, SkillGroupItem, SkillGroupItemHistoryRequest, SkillsGroupsItemsList, SkillsGroupsList, SkillsGroupsServiceCreateRequest, SkillsGroupsServiceEntityPaginationReq, SkillsGroupsServiceFilterReq, SkillsGroupsServiceItemCreateRequest, SkillsGroupsServiceItemUpdateRequest, SkillsGroupsServicePaginationReq, SkillsGroupsServicePaginationResponse, SkillsGroupsServiceSearchAllReq, SkillsGroupsServiceUpdateRequest ***REMOVED*** from "./skills_groups_pb.js";
import ***REMOVED*** ActiveStatus, CloneRequest, CountInSLCStatusRequest, CountResponse, Identifier, IdentifierUUID, IdentifierWithSearchKey, IdentifierWithUserComment, ReorderItemsRequest ***REMOVED*** from "./base_pb.js";
import ***REMOVED*** MethodKind ***REMOVED*** from "@bufbuild/protobuf";

/**
 *
 * Describes the common methods applicable on each skill group
 *
 * @generated from service Genesis.SkillsGroupsService
 */
export const SkillsGroupsService = ***REMOVED***
  typeName: "Genesis.SkillsGroupsService",
  methods: ***REMOVED***
    /**
     * Create and send for verification
     *
     * @generated from rpc Genesis.SkillsGroupsService.Create
     */
    create: ***REMOVED***
      name: "Create",
      I: SkillsGroupsServiceCreateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Create and save as draft
     *
     * @generated from rpc Genesis.SkillsGroupsService.Draft
     */
    draft: ***REMOVED***
      name: "Draft",
      I: SkillsGroupsServiceCreateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Update draft
     *
     * @generated from rpc Genesis.SkillsGroupsService.DraftUpdate
     */
    draftUpdate: ***REMOVED***
      name: "DraftUpdate",
      I: SkillsGroupsServiceUpdateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Send for verification
     *
     * @generated from rpc Genesis.SkillsGroupsService.SendForVerification
     */
    sendForVerification: ***REMOVED***
      name: "SendForVerification",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Verify
     *
     * @generated from rpc Genesis.SkillsGroupsService.Verify
     */
    verify: ***REMOVED***
      name: "Verify",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Approve
     *
     * @generated from rpc Genesis.SkillsGroupsService.Approve
     */
    approve: ***REMOVED***
      name: "Approve",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Send For Revision
     *
     * @generated from rpc Genesis.SkillsGroupsService.SendForRevision
     */
    sendForRevision: ***REMOVED***
      name: "SendForRevision",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Update revision
     *
     * @generated from rpc Genesis.SkillsGroupsService.RevisionUpdate
     */
    revisionUpdate: ***REMOVED***
      name: "RevisionUpdate",
      I: SkillsGroupsServiceUpdateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Halt
     *
     * @generated from rpc Genesis.SkillsGroupsService.Halt
     */
    halt: ***REMOVED***
      name: "Halt",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Discard
     *
     * @generated from rpc Genesis.SkillsGroupsService.Discard
     */
    discard: ***REMOVED***
      name: "Discard",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Restore
     *
     * @generated from rpc Genesis.SkillsGroupsService.Restore
     */
    restore: ***REMOVED***
      name: "Restore",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Complete
     *
     * @generated from rpc Genesis.SkillsGroupsService.Complete
     */
    complete: ***REMOVED***
      name: "Complete",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Repeat
     *
     * @generated from rpc Genesis.SkillsGroupsService.Repeat
     */
    repeat: ***REMOVED***
      name: "Repeat",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Reopen
     *
     * @generated from rpc Genesis.SkillsGroupsService.Reopen
     */
    reopen: ***REMOVED***
      name: "Reopen",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Add comment
     *
     * Send Email
     * rpc SendEmail (IdentifierWithEmailAttributes) returns (Identifier);
     *
     * @generated from rpc Genesis.SkillsGroupsService.CommentAdd
     */
    commentAdd: ***REMOVED***
      name: "CommentAdd",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Clone skill group from an existing skill group (denoted by the identifier)
     *
     * @generated from rpc Genesis.SkillsGroupsService.Clone
     */
    clone: ***REMOVED***
      name: "Clone",
      I: CloneRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Add a param to a skill group
     *
     * @generated from rpc Genesis.SkillsGroupsService.AddSkillGroupItem
     */
    addSkillGroupItem: ***REMOVED***
      name: "AddSkillGroupItem",
      I: SkillsGroupsServiceItemCreateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Modify a param in a skill group
     *
     * @generated from rpc Genesis.SkillsGroupsService.ModifySkillGroupItem
     */
    modifySkillGroupItem: ***REMOVED***
      name: "ModifySkillGroupItem",
      I: SkillsGroupsServiceItemUpdateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Approve a param in a skill group
     *
     * @generated from rpc Genesis.SkillsGroupsService.ApproveSkillGroupItem
     */
    approveSkillGroupItem: ***REMOVED***
      name: "ApproveSkillGroupItem",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Delete a param in a skill group
     *
     * @generated from rpc Genesis.SkillsGroupsService.DeleteSkillGroupItem
     */
    deleteSkillGroupItem: ***REMOVED***
      name: "DeleteSkillGroupItem",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Reorder params in a skill group
     *
     * @generated from rpc Genesis.SkillsGroupsService.ReorderSkillGroupItems
     */
    reorderSkillGroupItems: ***REMOVED***
      name: "ReorderSkillGroupItems",
      I: ReorderItemsRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View Skill Group Item by ID
     *
     * @generated from rpc Genesis.SkillsGroupsService.ViewSkillGroupItemByID
     */
    viewSkillGroupItemByID: ***REMOVED***
      name: "ViewSkillGroupItemByID",
      I: Identifier,
      O: SkillGroupItem,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View approved skill group params for given skill group ID
     *
     * @generated from rpc Genesis.SkillsGroupsService.ViewApprovedSkillGroupItems
     */
    viewApprovedSkillGroupItems: ***REMOVED***
      name: "ViewApprovedSkillGroupItems",
      I: IdentifierWithSearchKey,
      O: SkillsGroupsItemsList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View unapproved skill group params for given skill group ID
     *
     * @generated from rpc Genesis.SkillsGroupsService.ViewUnapprovedSkillGroupItems
     */
    viewUnapprovedSkillGroupItems: ***REMOVED***
      name: "ViewUnapprovedSkillGroupItems",
      I: IdentifierWithSearchKey,
      O: SkillsGroupsItemsList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View the history of the skill group item
     *
     * @generated from rpc Genesis.SkillsGroupsService.ViewSkillGroupItemHistory
     */
    viewSkillGroupItemHistory: ***REMOVED***
      name: "ViewSkillGroupItemHistory",
      I: SkillGroupItemHistoryRequest,
      O: SkillsGroupsItemsList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View by ID
     *
     * @generated from rpc Genesis.SkillsGroupsService.ViewByID
     */
    viewByID: ***REMOVED***
      name: "ViewByID",
      I: Identifier,
      O: SkillGroup,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View all
     *
     * @generated from rpc Genesis.SkillsGroupsService.ViewAll
     */
    viewAll: ***REMOVED***
      name: "ViewAll",
      I: ActiveStatus,
      O: SkillsGroupsList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View all with the given entity UUID
     *
     * @generated from rpc Genesis.SkillsGroupsService.ViewAllForEntityUUID
     */
    viewAllForEntityUUID: ***REMOVED***
      name: "ViewAllForEntityUUID",
      I: IdentifierUUID,
      O: SkillsGroupsList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View with pagination
     *
     * @generated from rpc Genesis.SkillsGroupsService.ViewWithPagination
     */
    viewWithPagination: ***REMOVED***
      name: "ViewWithPagination",
      I: SkillsGroupsServicePaginationReq,
      O: SkillsGroupsServicePaginationResponse,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View with pagination with the given entity UUID
     *
     * @generated from rpc Genesis.SkillsGroupsService.ViewWithPaginationForEntityUUID
     */
    viewWithPaginationForEntityUUID: ***REMOVED***
      name: "ViewWithPaginationForEntityUUID",
      I: SkillsGroupsServiceEntityPaginationReq,
      O: SkillsGroupsServicePaginationResponse,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View the latest skill group for a role (denoted by the given identifier)
     *
     * @generated from rpc Genesis.SkillsGroupsService.ViewForRoleID
     */
    viewForRoleID: ***REMOVED***
      name: "ViewForRoleID",
      I: Identifier,
      O: SkillGroup,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View all that match the given search key
     *
     * @generated from rpc Genesis.SkillsGroupsService.SearchAll
     */
    searchAll: ***REMOVED***
      name: "SearchAll",
      I: SkillsGroupsServiceSearchAllReq,
      O: SkillsGroupsList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View all that match the given filter criteria
     *
     * @generated from rpc Genesis.SkillsGroupsService.Filter
     */
    filter: ***REMOVED***
      name: "Filter",
      I: SkillsGroupsServiceFilterReq,
      O: SkillsGroupsList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Count in status
     *
     * @generated from rpc Genesis.SkillsGroupsService.CountInStatus
     */
    countInStatus: ***REMOVED***
      name: "CountInStatus",
      I: CountInSLCStatusRequest,
      O: CountResponse,
      kind: MethodKind.Unary,
***REMOVED***
  ***REMOVED***
***REMOVED*** as const;

