// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=ts"
// @generated from file work_orders.proto (package Genesis, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import ***REMOVED*** WorkOrder, WorkOrderItem, WorkOrderItemHistoryRequest, WorkOrderItemProspectiveInfoRequest, WorkOrdersItemsList, WorkOrdersList, WorkOrdersServiceAutofillRequest, WorkOrdersServiceCreateRequest, WorkOrdersServiceEntityPaginationReq, WorkOrdersServiceFilterReq, WorkOrdersServiceItemCreateRequest, WorkOrdersServiceItemUpdateRequest, WorkOrdersServicePaginationReq, WorkOrdersServicePaginationResponse, WorkOrdersServiceSearchAllReq, WorkOrdersServiceUpdateRequest ***REMOVED*** from "./work_orders_pb.js";
import ***REMOVED*** ActiveStatus, BooleanResponse, CountInSLCStatusRequest, CountResponse, Identifier, IdentifierUUID, IdentifierWithEmailAttributes, IdentifierWithSearchKey, IdentifierWithUserComment, ReorderItemsRequest ***REMOVED*** from "./base_pb.js";
import ***REMOVED*** MethodKind ***REMOVED*** from "@bufbuild/protobuf";
import ***REMOVED*** FamiliesList ***REMOVED*** from "./families_pb.js";

/**
 *
 * Describes the common methods applicable on each work order
 *
 * @generated from service Genesis.WorkOrdersService
 */
export const WorkOrdersService = ***REMOVED***
  typeName: "Genesis.WorkOrdersService",
  methods: ***REMOVED***
    /**
     * Create and send for verification
     *
     * @generated from rpc Genesis.WorkOrdersService.Create
     */
    create: ***REMOVED***
      name: "Create",
      I: WorkOrdersServiceCreateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Create and save as draft
     *
     * @generated from rpc Genesis.WorkOrdersService.Draft
     */
    draft: ***REMOVED***
      name: "Draft",
      I: WorkOrdersServiceCreateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Update draft
     *
     * @generated from rpc Genesis.WorkOrdersService.DraftUpdate
     */
    draftUpdate: ***REMOVED***
      name: "DraftUpdate",
      I: WorkOrdersServiceUpdateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Send for verification
     *
     * @generated from rpc Genesis.WorkOrdersService.SendForVerification
     */
    sendForVerification: ***REMOVED***
      name: "SendForVerification",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Verify
     *
     * @generated from rpc Genesis.WorkOrdersService.Verify
     */
    verify: ***REMOVED***
      name: "Verify",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Approve
     *
     * @generated from rpc Genesis.WorkOrdersService.Approve
     */
    approve: ***REMOVED***
      name: "Approve",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Send For Revision
     *
     * @generated from rpc Genesis.WorkOrdersService.SendForRevision
     */
    sendForRevision: ***REMOVED***
      name: "SendForRevision",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Update revision
     *
     * @generated from rpc Genesis.WorkOrdersService.RevisionUpdate
     */
    revisionUpdate: ***REMOVED***
      name: "RevisionUpdate",
      I: WorkOrdersServiceUpdateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Halt
     *
     * @generated from rpc Genesis.WorkOrdersService.Halt
     */
    halt: ***REMOVED***
      name: "Halt",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Discard
     *
     * @generated from rpc Genesis.WorkOrdersService.Discard
     */
    discard: ***REMOVED***
      name: "Discard",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Restore
     *
     * @generated from rpc Genesis.WorkOrdersService.Restore
     */
    restore: ***REMOVED***
      name: "Restore",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Complete
     *
     * @generated from rpc Genesis.WorkOrdersService.Complete
     */
    complete: ***REMOVED***
      name: "Complete",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Repeat
     *
     * @generated from rpc Genesis.WorkOrdersService.Repeat
     */
    repeat: ***REMOVED***
      name: "Repeat",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Reopen
     *
     * @generated from rpc Genesis.WorkOrdersService.Reopen
     */
    reopen: ***REMOVED***
      name: "Reopen",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Add comment
     *
     * @generated from rpc Genesis.WorkOrdersService.CommentAdd
     */
    commentAdd: ***REMOVED***
      name: "CommentAdd",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Send Email
     *
     * @generated from rpc Genesis.WorkOrdersService.SendEmail
     */
    sendEmail: ***REMOVED***
      name: "SendEmail",
      I: IdentifierWithEmailAttributes,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Autofill the work order
     *
     * @generated from rpc Genesis.WorkOrdersService.Autofill
     */
    autofill: ***REMOVED***
      name: "Autofill",
      I: WorkOrdersServiceAutofillRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Checks if the Work Order can be marked as completed
     *
     * @generated from rpc Genesis.WorkOrdersService.IsCompletable
     */
    isCompletable: ***REMOVED***
      name: "IsCompletable",
      I: Identifier,
      O: BooleanResponse,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Add an item to a work order
     *
     * @generated from rpc Genesis.WorkOrdersService.AddWorkOrderItem
     */
    addWorkOrderItem: ***REMOVED***
      name: "AddWorkOrderItem",
      I: WorkOrdersServiceItemCreateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Modify an item in a work order
     *
     * @generated from rpc Genesis.WorkOrdersService.ModifyWorkOrderItem
     */
    modifyWorkOrderItem: ***REMOVED***
      name: "ModifyWorkOrderItem",
      I: WorkOrdersServiceItemUpdateRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Approve an item in a work order
     *
     * @generated from rpc Genesis.WorkOrdersService.ApproveWorkOrderItem
     */
    approveWorkOrderItem: ***REMOVED***
      name: "ApproveWorkOrderItem",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Delete an item in a work order
     *
     * @generated from rpc Genesis.WorkOrdersService.DeleteWorkOrderItem
     */
    deleteWorkOrderItem: ***REMOVED***
      name: "DeleteWorkOrderItem",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Reorder items in a work order
     *
     * @generated from rpc Genesis.WorkOrdersService.ReorderWorkOrderItems
     */
    reorderWorkOrderItems: ***REMOVED***
      name: "ReorderWorkOrderItems",
      I: ReorderItemsRequest,
      O: Identifier,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View Work Order Item by ID
     *
     * @generated from rpc Genesis.WorkOrdersService.ViewWorkOrderItemByID
     */
    viewWorkOrderItemByID: ***REMOVED***
      name: "ViewWorkOrderItemByID",
      I: Identifier,
      O: WorkOrderItem,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View approved work order items for given work order ID
     *
     * @generated from rpc Genesis.WorkOrdersService.ViewApprovedWorkOrderItems
     */
    viewApprovedWorkOrderItems: ***REMOVED***
      name: "ViewApprovedWorkOrderItems",
      I: IdentifierWithSearchKey,
      O: WorkOrdersItemsList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View unapproved work order items for given work order ID
     *
     * @generated from rpc Genesis.WorkOrdersService.ViewUnapprovedWorkOrderItems
     */
    viewUnapprovedWorkOrderItems: ***REMOVED***
      name: "ViewUnapprovedWorkOrderItems",
      I: IdentifierWithSearchKey,
      O: WorkOrdersItemsList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View the history of the work order item
     *
     * @generated from rpc Genesis.WorkOrdersService.ViewWorkOrderItemHistory
     */
    viewWorkOrderItemHistory: ***REMOVED***
      name: "ViewWorkOrderItemHistory",
      I: WorkOrderItemHistoryRequest,
      O: WorkOrdersItemsList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View by ID
     *
     * @generated from rpc Genesis.WorkOrdersService.ViewByID
     */
    viewByID: ***REMOVED***
      name: "ViewByID",
      I: Identifier,
      O: WorkOrder,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View all
     *
     * @generated from rpc Genesis.WorkOrdersService.ViewAll
     */
    viewAll: ***REMOVED***
      name: "ViewAll",
      I: ActiveStatus,
      O: WorkOrdersList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View all with the given entity UUID
     *
     * @generated from rpc Genesis.WorkOrdersService.ViewAllForEntityUUID
     */
    viewAllForEntityUUID: ***REMOVED***
      name: "ViewAllForEntityUUID",
      I: IdentifierUUID,
      O: WorkOrdersList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View with pagination
     *
     * @generated from rpc Genesis.WorkOrdersService.ViewWithPagination
     */
    viewWithPagination: ***REMOVED***
      name: "ViewWithPagination",
      I: WorkOrdersServicePaginationReq,
      O: WorkOrdersServicePaginationResponse,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View with pagination with the given entity UUID
     *
     * @generated from rpc Genesis.WorkOrdersService.ViewWithPaginationForEntityUUID
     */
    viewWithPaginationForEntityUUID: ***REMOVED***
      name: "ViewWithPaginationForEntityUUID",
      I: WorkOrdersServiceEntityPaginationReq,
      O: WorkOrdersServicePaginationResponse,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View prospective families for the given work order
     *
     * @generated from rpc Genesis.WorkOrdersService.ViewProspectiveFamilies
     */
    viewProspectiveFamilies: ***REMOVED***
      name: "ViewProspectiveFamilies",
      I: IdentifierWithSearchKey,
      O: FamiliesList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View prospective work order item info for the given family ID and work order ID
     *
     * @generated from rpc Genesis.WorkOrdersService.ViewProspectiveWorkOrderItem
     */
    viewProspectiveWorkOrderItem: ***REMOVED***
      name: "ViewProspectiveWorkOrderItem",
      I: WorkOrderItemProspectiveInfoRequest,
      O: WorkOrdersServiceItemCreateRequest,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View all that match the given search key
     *
     * @generated from rpc Genesis.WorkOrdersService.SearchAll
     */
    searchAll: ***REMOVED***
      name: "SearchAll",
      I: WorkOrdersServiceSearchAllReq,
      O: WorkOrdersList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * View all that match the given filter criteria
     *
     * @generated from rpc Genesis.WorkOrdersService.Filter
     */
    filter: ***REMOVED***
      name: "Filter",
      I: WorkOrdersServiceFilterReq,
      O: WorkOrdersList,
      kind: MethodKind.Unary,
***REMOVED***
    /**
     * Count in status
     *
     * @generated from rpc Genesis.WorkOrdersService.CountInStatus
     */
    countInStatus: ***REMOVED***
      name: "CountInStatus",
      I: CountInSLCStatusRequest,
      O: CountResponse,
      kind: MethodKind.Unary,
***REMOVED***
  ***REMOVED***
***REMOVED*** as const;

